In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
data=pd.read_csv("insurance.csv")
data

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [34]:
data["bmi"]=data["bmi"].astype(int)
data["charges"]=data["charges"].astype(int)

In [35]:
x=data.iloc[:, :-1].values
y=data.iloc[:,-1].values

In [36]:
x

array([[19, 'female', 27, 0, 'yes', 'southwest'],
       [18, 'male', 33, 1, 'no', 'southeast'],
       [28, 'male', 33, 3, 'no', 'southeast'],
       [33, 'male', 22, 0, 'no', 'northwest'],
       [32, 'male', 28, 0, 'no', 'northwest'],
       [31, 'female', 25, 0, 'no', 'southeast'],
       [46, 'female', 33, 1, 'no', 'southeast'],
       [37, 'female', 27, 3, 'no', 'northwest'],
       [37, 'male', 29, 2, 'no', 'northeast'],
       [60, 'female', 25, 0, 'no', 'northwest'],
       [25, 'male', 26, 0, 'no', 'northeast'],
       [62, 'female', 26, 0, 'yes', 'southeast'],
       [23, 'male', 34, 0, 'no', 'southwest'],
       [56, 'female', 39, 0, 'no', 'southeast'],
       [27, 'male', 42, 0, 'yes', 'southeast'],
       [19, 'male', 24, 1, 'no', 'southwest'],
       [52, 'female', 30, 1, 'no', 'northeast'],
       [23, 'male', 23, 0, 'no', 'northeast'],
       [56, 'male', 40, 0, 'no', 'southwest'],
       [30, 'male', 35, 0, 'yes', 'southwest'],
       [60, 'female', 36, 0, 'no', 'nort

In [37]:
y

array([16884,  1725,  4449, 21984,  3866,  3756,  8240,  7281,  6406,
       28923,  2721, 27808,  1826, 11090, 39611,  1837, 10797,  2395,
       10602, 36837, 13228,  4149,  1137, 37701,  6203, 14001, 14451,
       12268,  2775, 38711, 35585,  2198,  4687, 13770, 51194,  1625,
       15612,  2302, 39774, 48173,  3046,  4949,  6272,  6313,  6079,
       20630,  3393,  3556, 12629, 38709,  2211,  3579, 23568, 37742,
        8059, 47496, 13607, 34303, 23244,  5989,  8606,  4504, 30166,
        4133, 14711,  1743, 14235,  6389,  5920, 17663, 16577,  6799,
       11741, 11946,  7726, 11356,  3947,  1532,  2755,  6571,  4441,
        7935, 37165, 11033, 39836, 21098, 43578, 11073,  8026, 11082,
        2026, 10942, 30184,  5729, 47291,  3766, 12105, 10226, 22412,
       15820,  6186,  3645, 21344, 30942,  5003, 17560,  2331,  3877,
        2867, 47055, 10825, 11881,  4646,  2404, 11488, 30259, 11381,
       19107,  8601,  6686,  7740,  1705,  2257, 39556, 10115,  3385,
       17081,  9634,

### Encode Categorical Data

In [38]:
## Gender
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,1]=le.fit_transform(x[:,1])
x[:,4]=le.fit_transform(x[:,4])
x

array([[19, 0, 27, 0, 1, 'southwest'],
       [18, 1, 33, 1, 0, 'southeast'],
       [28, 1, 33, 3, 0, 'southeast'],
       [33, 1, 22, 0, 0, 'northwest'],
       [32, 1, 28, 0, 0, 'northwest'],
       [31, 0, 25, 0, 0, 'southeast'],
       [46, 0, 33, 1, 0, 'southeast'],
       [37, 0, 27, 3, 0, 'northwest'],
       [37, 1, 29, 2, 0, 'northeast'],
       [60, 0, 25, 0, 0, 'northwest'],
       [25, 1, 26, 0, 0, 'northeast'],
       [62, 0, 26, 0, 1, 'southeast'],
       [23, 1, 34, 0, 0, 'southwest'],
       [56, 0, 39, 0, 0, 'southeast'],
       [27, 1, 42, 0, 1, 'southeast'],
       [19, 1, 24, 1, 0, 'southwest'],
       [52, 0, 30, 1, 0, 'northeast'],
       [23, 1, 23, 0, 0, 'northeast'],
       [56, 1, 40, 0, 0, 'southwest'],
       [30, 1, 35, 0, 1, 'southwest'],
       [60, 0, 36, 0, 0, 'northeast'],
       [30, 0, 32, 1, 0, 'southwest'],
       [18, 1, 34, 0, 0, 'southeast'],
       [34, 0, 31, 1, 1, 'northeast'],
       [37, 1, 28, 2, 0, 'northwest'],
       [59, 0, 27, 3, 0, 

In [39]:
#region
np.set_printoptions(threshold=np.sys.maxsize)
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [5])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [40]:
x[:3]

array([[0.0, 0.0, 0.0, 1.0, 19, 0, 27, 0, 1],
       [0.0, 0.0, 1.0, 0.0, 18, 1, 33, 1, 0],
       [0.0, 0.0, 1.0, 0.0, 28, 1, 33, 3, 0]], dtype=object)

## Test Train Split

In [41]:
from sklearn.model_selection import train_test_split

In [42]:
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2, random_state=43)

## Training the Multiple Linear Regression model on the Training set

In [43]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

## ## Predicting the Test set results using the class


In [44]:
y_pred=regressor.predict(x_test) #### Vector of PREDICTED cost (x_Test)

In [45]:
np.set_printoptions(precision=2)

In [46]:
print(np.concatenate((y_pred.reshape(len(y_pred), 1),y_test.reshape(len(y_test),1)),1))


[[ 8155.84 18963.  ]
 [ 6152.39 13725.  ]
 [ 2555.48  2457.  ]
 [15227.53 12979.  ]
 [27997.42 18648.  ]
 [ 9967.55  6551.  ]
 [10749.16  7160.  ]
 [ 7277.01 19442.  ]
 [ 9863.61  8280.  ]
 [ 1520.72  1708.  ]
 [27236.82 34828.  ]
 [24955.69 14571.  ]
 [ 9680.04 11070.  ]
 [ 9393.62  7358.  ]
 [ 2355.98  1967.  ]
 [ 5288.43  4527.  ]
 [ 2776.21  4134.  ]
 [27040.25 17043.  ]
 [ 7145.8   2689.  ]
 [ 3680.49 17626.  ]
 [ 4983.71  4877.  ]
 [12173.66 12913.  ]
 [ 2233.87  2257.  ]
 [11537.96  9630.  ]
 [ 6950.01 14358.  ]
 [ 7330.44  6555.  ]
 [11004.72 18806.  ]
 [40510.53 48970.  ]
 [ 2402.67  3561.  ]
 [12547.26  9634.  ]
 [14778.87 13143.  ]
 [31921.1  38282.  ]
 [15623.7  16455.  ]
 [ 1794.92  3260.  ]
 [12263.4  10461.  ]
 [ 4166.11  2055.  ]
 [ 7910.16  4670.  ]
 [12641.36 25333.  ]
 [10461.82 11454.  ]
 [ 5828.3  11737.  ]
 [27751.62 17663.  ]
 [28184.34 34838.  ]
 [ 3761.27  4185.  ]
 [13747.19 10848.  ]
 [11030.46  8596.  ]
 [34268.74 25309.  ]
 [12069.94 11735.  ]
 [ 2844.91 11

In [47]:
## 1 column - predicted profits, 2 column - real profits


## Backward Elimination - Manual Elimination

In [48]:
x=x[:,1:] ## to avoid dummy trap 
len(x)

1338

In [49]:
np.set_printoptions(threshold=np.sys.maxsize)

In [50]:
import statsmodels.api as sm
## Create the b0
x=np.append(arr=np.ones((len(x),1)).astype(int),values=x,axis=1)
x[:10]

array([[1, 0.0, 0.0, 1.0, 19, 0, 27, 0, 1],
       [1, 0.0, 1.0, 0.0, 18, 1, 33, 1, 0],
       [1, 0.0, 1.0, 0.0, 28, 1, 33, 3, 0],
       [1, 1.0, 0.0, 0.0, 33, 1, 22, 0, 0],
       [1, 1.0, 0.0, 0.0, 32, 1, 28, 0, 0],
       [1, 0.0, 1.0, 0.0, 31, 0, 25, 0, 0],
       [1, 0.0, 1.0, 0.0, 46, 0, 33, 1, 0],
       [1, 1.0, 0.0, 0.0, 37, 0, 27, 3, 0],
       [1, 0.0, 0.0, 0.0, 37, 1, 29, 2, 0],
       [1, 1.0, 0.0, 0.0, 60, 0, 25, 0, 0]], dtype=object)

In [51]:
x_opt=x[:,[0,1,2,3,4,5,6,7,8]]
x_opt=x_opt.astype(np.float64)

In [52]:
#Step 2: Fit the full model  with all possible predictors
regressor_OLS=sm.OLS(endog=y,exog=x_opt).fit()
# endog is dependent variable, exog - regressor

Ordinary least-squares (OLS) models assume that the analysis is fitting a model of a relationship between one or more explanatory variables and a continuous or at least interval outcome variable that minimizes the sum of square errors, where an error is the difference between the actual and the predicted value of the

In [53]:
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.751
Model:                            OLS   Adj. R-squared:                  0.749
Method:                 Least Squares   F-statistic:                     500.7
Date:                Tue, 08 Dec 2020   Prob (F-statistic):               0.00
Time:                        10:38:33   Log-Likelihood:                -13548.
No. Observations:                1338   AIC:                         2.711e+04
Df Residuals:                    1329   BIC:                         2.716e+04
Df Model:                           8                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -1.174e+04    975.287    -12.040      0.000   -1.37e+04   -9828.717
x1          -346.4653    476.304     -0.727      0.467   -1280.856     587.925
x2         -1042.4467    478.895     -2.177      0.030   -1981.920    -102.974
x3          -969.5708    478.032     -2.028      0.043   -1907.350     -31.791
x4           256.9773     11.898     21.597      0.000     233.635     280.319
x5          -132.4209    332.971     -0.398      0.691    -785.626     520.784
x6           337.9905     28.516     11.853      0.000     282.050     393.931
x7           478.2346    137.810      3.470      0.001     207.886     748.583
x8          2.386e+04    413.194     57.745      0.000     2.3e+04    2.47e+04
==============================================================================
Omnibus:                      299.844   Durbin-Watson:                   2.089
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              716.591
Skew:                           1.210   Prob(JB):                    2.48e-156
Kurtosis:                       5.646   Cond. No.                         306.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [54]:
x[:3]

array([[1, 0.0, 0.0, 1.0, 19, 0, 27, 0, 1],
       [1, 0.0, 1.0, 0.0, 18, 1, 33, 1, 0],
       [1, 0.0, 1.0, 0.0, 28, 1, 33, 3, 0]], dtype=object)

 ### Now we need to get rid of the variables, with the highest p-values (everything that is higher 0.05)

In [55]:
#x5 has the highest p-value: 0.693 - this is the gender, so the gender has less  significant influence on the cost
x_opt=x[:,[0,1,2,3,4,6,7,8]]
x_opt=x_opt.astype(np.float64)
regressor_OLS=sm.OLS(endog=y, exog=x_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.751
Model:                            OLS   Adj. R-squared:                  0.750
Method:                 Least Squares   F-statistic:                     572.6
Date:                Tue, 08 Dec 2020   Prob (F-statistic):               0.00
Time:                        10:38:38   Log-Likelihood:                -13548.
No. Observations:                1338   AIC:                         2.711e+04
Df Residuals:                    1330   BIC:                         2.715e+04
Df Model:                           7                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -1.179e+04    966.050    -12.209      0.000   -1.37e+04   -9899.214
x1          -345.6872    476.150     -0.726      0.468   -1279.773     588.399
x2         -1041.7512    478.740     -2.176      0.030   -1980.920    -102.583
x3          -968.8683    477.877     -2.027      0.043   -1906.344     -31.393
x4           257.0955     11.891     21.621      0.000     233.768     280.423
x5           337.4552     28.475     11.851      0.000     281.594     393.316
x6           477.2887    137.746      3.465      0.001     207.066     747.511
x7          2.385e+04    411.894     57.897      0.000     2.3e+04    2.47e+04
==============================================================================
Omnibus:                      300.206   Durbin-Watson:                   2.090
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              718.195
Skew:                           1.211   Prob(JB):                    1.11e-156
Kurtosis:                       5.649   Cond. No.                         303.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [56]:
x[:3]

array([[1, 0.0, 0.0, 1.0, 19, 0, 27, 0, 1],
       [1, 0.0, 1.0, 0.0, 18, 1, 33, 1, 0],
       [1, 0.0, 1.0, 0.0, 28, 1, 33, 3, 0]], dtype=object)

In [57]:
## Again x1 has the highest p-values, 0.878
x_opt=x[:,[0,2,3,4,6,7,8]]
x_opt=x_opt.astype(np.float64)
regressor_OLS=sm.OLS(endog=y,exog=x_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.751
Model:                            OLS   Adj. R-squared:                  0.750
Method:                 Least Squares   F-statistic:                     668.2
Date:                Tue, 08 Dec 2020   Prob (F-statistic):               0.00
Time:                        10:38:40   Log-Likelihood:                -13548.
No. Observations:                1338   AIC:                         2.711e+04
Df Residuals:                    1331   BIC:                         2.715e+04
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -1.197e+04    936.196    -12.782      0.000   -1.38e+04   -1.01e+04
x1          -869.2051    415.507     -2.092      0.037   -1684.326     -54.085
x2          -795.5297    413.886     -1.922      0.055   -1607.469      16.409
x3           257.1265     11.889     21.628      0.000     233.804     280.449
x4           337.4563     28.470     11.853      0.000     281.605     393.307
x5           474.3205    137.660      3.446      0.001     204.265     744.376
x6          2.385e+04    411.693     57.943      0.000     2.3e+04    2.47e+04
==============================================================================
Omnibus:                      299.595   Durbin-Watson:                   2.093
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              714.289
Skew:                           1.210   Prob(JB):                    7.84e-156
Kurtosis:                       5.638   Cond. No.                         289.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [58]:
x_opt=x[:,[0,2,4,6,7,8]]
x_opt=x_opt.astype(np.float64)
regressor_OLS=sm.OLS(endog=y, exog=x_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.750
Model:                            OLS   Adj. R-squared:                  0.749
Method:                 Least Squares   F-statistic:                     799.5
Date:                Tue, 08 Dec 2020   Prob (F-statistic):               0.00
Time:                        10:38:42   Log-Likelihood:                -13550.
No. Observations:                1338   AIC:                         2.711e+04
Df Residuals:                    1332   BIC:                         2.714e+04
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -1.208e+04    935.354    -12.913      0.000   -1.39e+04   -1.02e+04
x1          -584.3832    388.578     -1.504      0.133   -1346.675     177.909
x2           257.2640     11.901     21.618      0.000     233.918     280.610
x3           332.0482     28.359     11.709      0.000     276.415     387.682
x4           470.7536    137.787      3.417      0.001     200.450     741.057
x5          2.386e+04    412.076     57.914      0.000    2.31e+04    2.47e+04
==============================================================================
Omnibus:                      302.400   Durbin-Watson:                   2.090
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              724.686
Skew:                           1.219   Prob(JB):                    4.33e-158
Kurtosis:                       5.657   Cond. No.                         289.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [59]:
x_opt=x[:,[0,4,6,7,8]]
x_opt=x_opt.astype(np.float64)
regressor_OLS=sm.OLS(endog=y, exog=x_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.750
Model:                            OLS   Adj. R-squared:                  0.749
Method:                 Least Squares   F-statistic:                     997.8
Date:                Tue, 08 Dec 2020   Prob (F-statistic):               0.00
Time:                        10:38:43   Log-Likelihood:                -13551.
No. Observations:                1338   AIC:                         2.711e+04
Df Residuals:                    1333   BIC:                         2.714e+04
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -1.191e+04    928.988    -12.819      0.000   -1.37e+04   -1.01e+04
x1           257.9823     11.897     21.685      0.000     234.644     281.320
x2           320.3293     27.281     11.742      0.000     266.812     373.847
x3           476.1474    137.806      3.455      0.001     205.808     746.487
x4          2.382e+04    411.261     57.923      0.000     2.3e+04    2.46e+04
==============================================================================
Omnibus:                      301.026   Durbin-Watson:                   2.088
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              720.158
Skew:                           1.214   Prob(JB):                    4.17e-157
Kurtosis:                       5.650   Cond. No.                         286.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [60]:
## Now the model is ready, with the backward elimination we have left only those variables that matter 

In [61]:
n=x[:,[0,4,6,7,8]]
n[:3]

array([[1, 19, 27, 0, 1],
       [1, 18, 33, 1, 0],
       [1, 28, 33, 3, 0]], dtype=object)

In [62]:
data

age     sex  bmi  children smoker     region  charges
0      19  female   27         0    yes  southwest    16884
1      18    male   33         1     no  southeast     1725
2      28    male   33         3     no  southeast     4449
3      33    male   22         0     no  northwest    21984
4      32    male   28         0     no  northwest     3866
...   ...     ...  ...       ...    ...        ...      ...
1333   50    male   30         3     no  northwest    10600
1334   18  female   31         0     no  northeast     2205
1335   18  female   36         0     no  southeast     1629
1336   21  female   25         0     no  southwest     2007
1337   61  female   29         0    yes  northwest    29141

[1338 rows x 7 columns]

## Variables that are statistically significant for our prediction:
  - Constant
  - Age
  - BMI
  - Children
  - Smoker Status